name: Publish Quarto Website

on:
  push:
    branches:
      - main   # or 'master' if that's your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Library Set Up
      # Step 2.1: Install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      # Step 2.2: Install R Markdown
      - name: Install rmarkdown
        run: Rscript -e "install.packages('rmarkdown')"
      # Step 2.3: Install KnitR
      - name: Install knitr
        run: Rscript -e "install.packages('knitr')"
      # Step 2.4: Install R packages required
      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('yaml', 'tibble', 'dplyr', 'purrr', 'DT'))"

      # Step 2.5: Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.47'  # or a specific version like '1.3.335'

      # Step 3: Render the website
      - name: Render Quarto site
        run: quarto render

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site   # default output folder for Quarto websites
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'


